import './globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'
import Link from "next/link";

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
          <nav className="px-20 flex justify-between mt-3">
              <Link href="/">Home</Link>
              <div className="flex items-center gap-x-8">
                  <Link href="/exhibition">Exhibition</Link>
                  <Link href="/about">About</Link>
              </div>
          </nav>
          {children}
      </body>
    </html>
  )
}
